name: Dev Bootstrap & Sanity
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  check:
    runs-on: windows-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Create venv & install deps
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\python.exe -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
            .\.venv\Scripts\python.exe -m pip install -r requirements.txt
          }
      - name: Run dev.ps1 (sanity check)
        shell: pwsh
        run: pwsh -File .\dev.ps1
